name: Deploy Production

on:
  push: 
    branches: ["main", "feat/cicd"]
    
jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    - name: Docker build
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: eggbot:latest
    - run: /usr/bin/docker save -o eggbot.tar eggbot:latest

    - name: Send docker image to server
      uses: appleboy/scp-action@master
      with:
        host: "backdoor.ballbot.dev"
        username: ${{ secrets.POSTOFFICE_NAME }}
        key : ${{ secrets.POSTOFFICE_KEY }}
        port: 22
        source: "eggbot.tar"
        target: "/home/postoffice/eggbot"

    - name: Bootup server
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: backdoor.ballbot.dev
        user: ${{ secrets.POSTOFFICE_NAME }}
        key: ${{ secrets.POSTOFFICE_KEY }}
        port: 22
        connect_timeout: 10s
        first_ssh: |
          docker stop eggbot || true
          docker rm eggbot || true
          docker image rm eggbot:latest
          docker load -i /home/postoffice/eggbot/eggbot.tar
          docker run -d -p 37463:3000 --name eggbot eggbot:latest
