name: Deploy Production

on:
  push: 
    branches: ["main"]
    
jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Docker build
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: eggbot:latest
    - run: /usr/bin/docker save -o eggbot.tar eggbot:latest

    - name: Send docker image to server
      uses: appleboy/scp-action@master
      with:
        host: "backdoor.ballbot.dev"
        username: ${{ secrets.POSTOFFICE_NAME }}
        key : ${{ secrets.POSTOFFICE_KEY }}
        port: 22
        source: "eggbot.tar"
        target: "/home/postoffice/eggbot"

    - name: Bootup server
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        EGGBOT_TOKEN: ${{ secrets.EGGBOT_TOKEN }}
        EGGBOT_CLIENT_ID: ${{ secrets.EGGBOT_CLIENT_ID }}
      with:
        host: backdoor.ballbot.dev
        user: ${{ secrets.POSTOFFICE_NAME }}
        key: ${{ secrets.POSTOFFICE_KEY }}
        port: 22
        connect_timeout: 10s
        first_ssh: |
          docker stop eggbot || true
          docker rm eggbot || true
          docker image rm eggbot:latest || true
          docker load -i /home/postoffice/eggbot/eggbot.tar
          docker run -d -p 37463:3000 -e DB_USER=$DB_USER -e DB_HOST=$DB_HOST -e DB_PASS=$DB_PASS -e DB_PORT=$DB_PORT -e DB_NAME=$DB_NAME -e EGGBOT_TOKEN=$EGGBOT_TOKEN -e EGGBOT_CLIENT_ID=$EGGBOT_CLIENT_ID --name eggbot eggbot:latest
