name: Deploy Production

on:
  push: 
    branches: ["main", "feat/cicd"]
    
jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    
