name: Deploy Production

on:
  push: 
    branches: ["main"]
    
jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
    - uses: actions/checkout@v3.3.0
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    - name: Docker build
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: eggbot:latest
    - run: /usr/bin/docker save -o eggbot.tar eggbot:latest
